version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  nginx:
    tty: true
    stdin_open: true
    container_name: ${NAMESPACE}_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80